# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b914649be472f8fb9b25894e023326f98586f7c8ee48849d0c19b4c0c230704bf0f38ae549de1650e2fd9960e457688de0b3a48f88f092633617d509d604a439

test:
  secret_key_base: 6517a2a5d84cc0a25c0b09c449b2ed212878541242fc5481b18e31b1d35458af78a26031905fe8632b0ec2080ee33da22c2b32c8a57de5794dec5d3fe6a561b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
